title: 我们男孩网
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wmnhw.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings add your name
author: 我们男孩网
author-pic: leach-face.jpg
about-author: 分享帅哥图片和视频的个人博客
#修改成你自己的
# Contact links
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

#修改成你自己的
email:
phone:
github:
jianshu:
juejin:
csdn:

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus修改成你自己的
discus_identifier: 我们男孩网
# Add your discus identifier

#intensedebate修改成你自己的
intensedebate_identifier:

# Tracker Google Analytics修改成你自己的
google-analysis:
baidu-analysis:


# Paginate
paginate: 18
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

imagepath: 

links:
  - name:         主页
    url:          https://sgxnsck.top
    external:     false
  - name:         关于
    url:          /about
    external:     false
  - name:         简导航
    url:          /jiandaohang
    external:     false
 

#添加分类步骤：
#1：在_config.yml links1及blog_中添加对应内容
#2：在_includes里面headr.html中添加对应内容
#3：在根目录blog文件中创建对应内容

label1: <span style="font-size:12px">Publish by
label2:  </span>


links1:
  - name:         所有
    url:          /
    type:         recent
    external:     false
  - name:         随笔
    url:          /myblog/essays
    type:         essays
    external:     false
  - name:         视频
    url:          /myblog/video
    type:         video
    external:     false
  - name:         图片
    url:          /myblog/image
    type:         image
    external:     false
  - name:        小说
    url:          /myblog/novel
    type:         image
    external:     false

blog_1:    recent
blog_2:    essays
blog_3:    video
blog_4:    image


#permalink: /:year/:month/:day/:title.html


timezone: Asia/Shanghai


# Valine评论系统开关
# Valine.
# You can get your appid and appkey from https://leancloud.app
# more info please open https://valine.js.org
valine:
  enable: true
  appid:  3BIBAU6V5KA6yhjMIHk30fmt-MdYXbMMI # your leancloud app id
  appkey: 2vtXjLOnka68I2MYOvSuIrij # your leancloud app key
  notify: true # mail notifier , https://github.com/xCss/Valine/wiki，v1.4.0+ 已废弃
  verify: true # Verification code，v1.4.0+ 已废弃
  placeholder: 在此处留言 # comment box placeholder
  avatar:   # gravatar style
  guest_info: 昵称,邮件,网址 # custom comment header
  pageSize: 10 # pagination size
  # path: window.location.pathname #  v1.4.0+不要使用参数“app_key: 'LHvLGcwcauE5B2JpMxJ3lbtF',”
  recordIP: true # 是否记录评论者IP
  enableQQ: true # 是否启用昵称框自动获取QQ昵称和QQ头像, 默认关闭
